[[plugins]]
    package = "netlify-plugin-11ty"
    [plugins.inputs]
        cache_img = './img'
        cache_img_httpHeader = false

        cache_assets = '../.cache'
        cache_other = ['../tweets']

[[redirects]]
  from = "https://11ty.owlish.dev/*"
  to = "https://www.ovl.design/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://reading.ovl.design/*"
  to = "https://www.ovl.design/around-the-web/"
  status = 301
  force = true

[[redirects]]
  from = "https://www.ovl.design/atw"
  to = "https://www.ovl.design/around-the-web/"
  status = 301
  force = true